# Generated by Django 4.2.9 on 2025-10-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the quiz', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the quiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Text of the answer')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is the correct answer')),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz Answers',
                'db_table': 'quiz_answers',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Text of the question')),
                ('order', models.IntegerField(default=0, help_text='Order of the question in the quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'quiz_questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score achieved (0-100)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=dict, help_text='Student answers stored as {question_id: answer_id}')),
                ('quiz', models.ForeignKey(help_text='Quiz that was submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Submission',
                'verbose_name_plural': 'Quiz Submissions',
                'db_table': 'quiz_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
