# Generated by Django 4.2.9 on 2025-10-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='student',
            field=models.ForeignKey(help_text='Student who submitted the quiz', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(help_text='Quiz this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(help_text='Question this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizquestion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Classroom this quiz is assigned to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classrooms.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('quiz', 'student')},
        ),
    ]
