# Generated by Django 4.2.11 on 2025-11-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_add_deadline_and_grading_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.IntegerField(help_text='Auto-calculated score (0-100)'),
        ),
    ]
