# Generated by Django 4.2.11 on 2025-11-05 04:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the layer', max_length=100)),
                ('data_source_table', models.CharField(help_text='Name of the PostGIS table containing the data', max_length=100)),
                ('geom_type', models.CharField(choices=[('POINT', 'Point'), ('LINESTRING', 'LineString'), ('POLYGON', 'Polygon'), ('MULTIPOINT', 'MultiPoint'), ('MULTILINESTRING', 'MultiLineString'), ('MULTIPOLYGON', 'MultiPolygon')], help_text='Geometry type stored in this layer', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the layer')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the layer is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Map Layer',
                'verbose_name_plural': 'Map Layers',
                'db_table': 'map_layers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VietnamProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Province name', max_length=100)),
                ('name_en', models.CharField(blank=True, help_text='Province name in English', max_length=100)),
                ('code', models.CharField(help_text='Province code', max_length=10, unique=True)),
                ('region', models.CharField(blank=True, help_text='Region (North, Central, South)', max_length=50)),
                ('population', models.IntegerField(blank=True, help_text='Population', null=True)),
                ('area_km2', models.FloatField(blank=True, help_text='Area in square kilometers', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Province boundary geometry', srid=4326)),
            ],
            options={
                'verbose_name': 'Vietnam Province',
                'verbose_name_plural': 'Vietnam Provinces',
                'db_table': 'vietnam_provinces',
                'ordering': ['name'],
            },
        ),
    ]
