# Generated by Django 4.2.11 on 2025-11-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='filter_column',
            field=models.CharField(blank=True, help_text='Optional column name to filter data (e.g., category)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='filter_value',
            field=models.CharField(blank=True, help_text='Optional value to filter by (e.g., truong_hoc)', max_length=100, null=True),
        ),
    ]
