# Generated by Django 4.2.11 on 2025-11-09 16:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0002_maplayer_filter_column_maplayer_filter_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the boundary', max_length=255)),
                ('type', models.CharField(blank=True, help_text='Type (e.g., district, ward)', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Administrative code', max_length=50)),
                ('population', models.IntegerField(blank=True, help_text='Population count', null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, help_text='Area in km²', max_digits=10, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Boundary geometry', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Boundary',
                'verbose_name_plural': 'Boundaries',
                'db_table': 'boundaries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the point of interest', max_length=255)),
                ('category', models.CharField(blank=True, help_text='Category/type (e.g., school, hospital)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the point')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Point location', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
                'db_table': 'points_of_interest',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the route', max_length=255)),
                ('type', models.CharField(blank=True, help_text='Type (e.g., bus, trail)', max_length=100)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, help_text='Length in km', max_digits=10, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Route geometry', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolygonFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the polygon feature', max_length=255)),
                ('category', models.CharField(help_text='Category/type (e.g., park, lake)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the feature')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Polygon geometry', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Polygon Feature',
                'verbose_name_plural': 'Polygon Features',
                'db_table': 'polygon_features',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='idx_polygon_features_category')],
            },
        ),
        migrations.CreateModel(
            name='LineFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the line feature', max_length=255)),
                ('category', models.CharField(help_text='Category/type (e.g., road, river)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the feature')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(help_text='Line geometry', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Line Feature',
                'verbose_name_plural': 'Line Features',
                'db_table': 'line_features',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='idx_line_features_category')],
            },
        ),
    ]
