# Generated by Django 4.2.11 on 2025-11-18 21:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0003_boundary_pointofinterest_route_polygonfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tinh', models.CharField(help_text='Province code', max_length=10, unique=True)),
                ('ten_tinh', models.CharField(help_text='Province name', max_length=255)),
                ('sap_nhap', models.TextField(blank=True, help_text='Merged provinces information')),
                ('quy_mo', models.TextField(blank=True, help_text='Scale information (districts, wards)')),
                ('tru_so', models.TextField(blank=True, help_text='Headquarters address')),
                ('loai', models.CharField(blank=True, help_text='Type (Tỉnh/Thành phố)', max_length=50)),
                ('cap', models.IntegerField(default=1, help_text='Administrative level')),
                ('stt', models.IntegerField(default=0, help_text='Sort order')),
                ('dtich_km2', models.DecimalField(blank=True, decimal_places=2, help_text='Area in km²', max_digits=10, null=True)),
                ('dan_so', models.IntegerField(blank=True, help_text='Population', null=True)),
                ('matdo_km2', models.DecimalField(blank=True, decimal_places=2, help_text='Population density per km²', max_digits=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Province boundary geometry', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'provinces',
                'ordering': ['stt', 'ten_tinh'],
                'indexes': [models.Index(fields=['ma_tinh'], name='idx_provinces_ma_tinh'), models.Index(fields=['ten_tinh'], name='idx_provinces_ten_tinh')],
            },
        ),
    ]
