# Generated by Django 4.2.11 on 2025-11-18 19:52

import apps.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0003_alter_classroom_teacher_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('description', models.TextField(help_text='Detailed assignment instructions')),
                ('due_date', models.DateTimeField(help_text='Deadline for submission')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, help_text='Maximum score for this assignment', max_digits=5)),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment (PDF, DOC, DOCX)', null=True, upload_to='assignments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), apps.core.validators.validate_assignment_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Classroom this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classrooms.classroom')),
                ('created_by', models.ForeignKey(help_text='Teacher who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Text answer (optional if file is provided)')),
                ('file', models.FileField(blank=True, help_text='File upload (PDF, DOC, DOCX)', null=True, upload_to='submissions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), apps.core.validators.validate_submission_file])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False, help_text='Flag indicating if submission was late')),
                ('assignment', models.ForeignKey(help_text='Assignment this submission is for', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classrooms.assignment')),
                ('student', models.ForeignKey(help_text='Student who submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Grade score', max_digits=5)),
                ('feedback', models.TextField(blank=True, help_text='Text feedback from teacher')),
                ('feedback_file', models.FileField(blank=True, help_text='Optional feedback file (PDF, DOC, DOCX)', null=True, upload_to='feedback/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), apps.core.validators.validate_feedback_file])),
                ('is_published', models.BooleanField(default=False, help_text='Whether grade is visible to student')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('graded_by', models.ForeignKey(help_text='Teacher who graded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(help_text='Submission being graded', on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='classrooms.submission')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student'], name='submissions_assignm_5339e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['classroom', 'due_date'], name='assignments_classro_73f793_idx'),
        ),
    ]
