# Generated by Django 4.2.9 on 2025-10-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the lesson', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'lessons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TOGGLE_LAYER', 'Toggle Layer'), ('ZOOM_TO', 'Zoom To Location'), ('HIGHLIGHT', 'Highlight Feature'), ('PAN_TO', 'Pan To Location'), ('SET_BASEMAP', 'Set Basemap'), ('SHOW_POPUP', 'Show Popup')], help_text='Type of map action to perform', max_length=50)),
                ('payload', models.JSONField(default=dict, help_text='JSON data containing action parameters (e.g., layer_id, coordinates)')),
            ],
            options={
                'verbose_name': 'Map Action',
                'verbose_name_plural': 'Map Actions',
                'db_table': 'map_actions',
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Order of the step in the lesson')),
                ('popup_text', models.TextField(help_text='Text to display to the student')),
                ('lesson', models.ForeignKey(help_text='Lesson this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lessons.lesson')),
                ('map_action', models.ForeignKey(blank=True, help_text='Map action to trigger with this step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_steps', to='lessons.mapaction')),
            ],
            options={
                'verbose_name': 'Lesson Step',
                'verbose_name_plural': 'Lesson Steps',
                'db_table': 'lesson_steps',
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
