# Generated by Django 4.2.11 on 2025-11-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Cơ bản'), ('Intermediate', 'Trung bình'), ('Advanced', 'Nâng cao')], default='Beginner', help_text='Difficulty level of the lesson', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='30 phút', help_text='Estimated duration (e.g., "30 phút", "1 giờ")', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('10', 'Lớp 10'), ('11', 'Lớp 11'), ('12', 'Lớp 12')], default='10', help_text='Grade level for this lesson', max_length=2),
        ),
        migrations.AddField(
            model_name='lesson',
            name='icon',
            field=models.CharField(choices=[('MapPin', 'Map Pin'), ('Map', 'Map'), ('Globe', 'Globe'), ('Target', 'Target'), ('BookOpen', 'Book Open')], default='BookOpen', help_text='Icon to display for this lesson', max_length=20),
        ),
    ]
